-- 000003_staging_agents.up.sql
-- Adds the "available agents" pool: agents that connected but aren't yet
-- assigned to a cluster. Operators can assign them to a cluster from the UI.

-- One-time tokens used by unassigned agents to register with the server.
-- Generated by an operator; not tied to any node or cluster.
CREATE TABLE staging_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash  TEXT NOT NULL UNIQUE,
    label       TEXT,                     -- optional operator note
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ
);

-- Unassigned agents that have registered with a staging token.
-- Once assigned to a cluster, a node record is created and the staging row
-- is deleted (or archived).
CREATE TABLE staging_agents (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hostname      TEXT NOT NULL,
    ip_address    TEXT,
    os            TEXT,
    arch          TEXT,
    agent_version TEXT,
    token_hash    TEXT NOT NULL UNIQUE,   -- permanent auth token (never shown again)
    status        TEXT NOT NULL DEFAULT 'connected'
                      CHECK (status IN ('connected', 'disconnected')),
    last_seen_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
