// Package configgen renders NetBox configuration.py files from cluster state.
package configgen

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"strings"
	"text/template"
)

// RenderInput holds every variable needed to produce a node-specific configuration.py.
type RenderInput struct {
	// Security
	SecretKey      string
	APITokenPepper string

	// Database (current Patroni primary IP, or node IP for standalone)
	DBHost     string
	DBPort     int
	DBName     string
	DBUser     string
	DBPassword string

	// Network
	AllowedHosts []string // hostname(s) and IP(s) for Django's ALLOWED_HOSTS

	// Redis / Sentinel
	SentinelAddrs        []string // "host:port" — defaults to ["127.0.0.1:26379"] if empty
	RedisTasksPassword   string
	RedisCachingPassword string
	PatroniScope         string // sentinel service name — matches the Patroni scope

	// Meta
	NetboxVersion string // "4.x" or "3.x"
}

// Render generates configuration.py content from the stored template and input.
// It returns the rendered content and its SHA-256 hex digest.
func Render(tmplSrc string, in RenderInput) (content, sha256hex string, err error) {
	// Migrate legacy pepper placeholder: old templates used {0: '{{.APITokenPepper}}'}
	// but APITokenPepper now holds the full dict literal.
	tmplSrc = strings.ReplaceAll(tmplSrc, `{0: '{{.APITokenPepper}}'}`, `{{.APITokenPepper}}`)

	if in.DBPort == 0 {
		in.DBPort = 5432
	}
	if len(in.SentinelAddrs) == 0 {
		in.SentinelAddrs = []string{"127.0.0.1:26379"}
	}

	data := struct {
		RenderInput
		AllowedHostsPy string
		SentinelsPy    string
		IsFourX        bool
	}{
		RenderInput:    in,
		AllowedHostsPy: toPyList(in.AllowedHosts),
		SentinelsPy:    sentinelsPy(in.SentinelAddrs),
		IsFourX:        strings.HasPrefix(in.NetboxVersion, "4"),
	}

	tmpl, err := template.New("config").Parse(tmplSrc)
	if err != nil {
		return "", "", fmt.Errorf("parsing config template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", "", fmt.Errorf("rendering config template: %w", err)
	}

	content = buf.String()
	sum := sha256.Sum256([]byte(content))
	return content, fmt.Sprintf("%x", sum[:]), nil
}

// DefaultTemplate returns a sensible starting template that operators can customise.
// It uses Go text/template syntax — {{.SecretKey}}, {{.DBHost}}, etc.
func DefaultTemplate() string {
	return defaultConfigTemplate
}

func toPyList(ss []string) string {
	if len(ss) == 0 {
		return "[]"
	}
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func sentinelsPy(addrs []string) string {
	parts := make([]string, 0, len(addrs))
	for _, addr := range addrs {
		i := strings.LastIndex(addr, ":")
		if i == -1 {
			parts = append(parts, fmt.Sprintf("(%q, 26379)", addr))
			continue
		}
		host, port := addr[:i], addr[i+1:]
		parts = append(parts, fmt.Sprintf("(%q, %s)", host, port))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// defaultConfigTemplate is the Go text/template source stored in new configs.
// Variables: {{.SecretKey}}, {{.APITokenPepper}}, {{.DBHost}}, {{.DBPort}},
//            {{.DBName}}, {{.DBUser}}, {{.DBPassword}},
//            {{.AllowedHostsPy}}, {{.SentinelsPy}},
//            {{.RedisTasksPassword}}, {{.RedisCachingPassword}},
//            {{.PatroniScope}}, {{.IsFourX}}
const defaultConfigTemplate = `# Generated by netbox-conductor — do not edit manually.
# Edit the template in the Configuration tab, then re-push to apply changes.

###########################################################
# Django
###########################################################

ALLOWED_HOSTS = {{.AllowedHostsPy}}

SECRET_KEY = '{{.SecretKey}}'
{{- if .IsFourX}}
API_TOKEN_PEPPERS = {{.APITokenPepper}}
{{- end}}

DEBUG = False

###########################################################
# Database (Patroni primary)
###########################################################

DATABASE = {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': '{{.DBName}}',
    'USER': '{{.DBUser}}',
    'PASSWORD': '{{.DBPassword}}',
    'HOST': '{{.DBHost}}',
    'PORT': '{{.DBPort}}',
    'CONN_MAX_AGE': 300,
}

###########################################################
# Redis / Sentinel
###########################################################

REDIS = {
    'tasks': {
        'SENTINELS': {{.SentinelsPy}},
        'SENTINEL_SERVICE': '{{.PatroniScope}}',
        'PASSWORD': '{{.RedisTasksPassword}}',
        'DATABASE': 0,
        'SSL': False,
    },
    'caching': {
        'SENTINELS': {{.SentinelsPy}},
        'SENTINEL_SERVICE': '{{.PatroniScope}}',
        'PASSWORD': '{{.RedisCachingPassword}}',
        'DATABASE': 1,
        'SSL': False,
    },
}

###########################################################
# Logging
###########################################################

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
    },
}
`
