package configgen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// PatroniInput holds variables for rendering a Patroni config (patroni.yml).
type PatroniInput struct {
	Scope       string // cluster name / Patroni scope
	NodeName    string // this node's hostname
	NodeAddr    string // this node's IP
	RaftSelfAddr  string // "IP:5433" for this node's Raft port
	RaftPartners  []string // "IP:5433" for peer data nodes
	WitnessAddr   string // "IP:port" of tool-server witness (empty if HA 3+)

	RESTUsername string // Patroni REST API basic-auth username
	RESTPassword string // Patroni REST API basic-auth password

	DBSuperUser   string
	DBSuperPass   string
	DBReplicaUser string
	DBReplicaPass string

	DataDir     string // Postgres data directory (e.g. /var/lib/postgresql/14/main)
	BinDir      string // Postgres bin directory (e.g. /usr/lib/postgresql/14/bin)
	ConnectAddr string // Postgres connect address (usually same as NodeAddr)
	Port        int    // Postgres port (default 5432)
}

// RenderPatroni renders a complete patroni.yml for one node.
func RenderPatroni(in PatroniInput) (string, error) {
	if in.Port == 0 {
		in.Port = 5432
	}
	if in.DataDir == "" {
		in.DataDir = "/var/lib/postgresql/14/main"
	}
	if in.BinDir == "" {
		in.BinDir = "/usr/lib/postgresql/14/bin"
	}
	if in.ConnectAddr == "" {
		in.ConnectAddr = in.NodeAddr
	}

	partners := make([]string, 0, len(in.RaftPartners))
	for _, p := range in.RaftPartners {
		partners = append(partners, fmt.Sprintf("  - %s", p))
	}

	data := struct {
		PatroniInput
		RaftPartnerLines string
		HasWitness       bool
	}{
		PatroniInput:    in,
		RaftPartnerLines: strings.Join(partners, "\n"),
		HasWitness:       in.WitnessAddr != "",
	}

	tmpl, err := template.New("patroni").Parse(patroniTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing patroni template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("rendering patroni config: %w", err)
	}
	return buf.String(), nil
}

const patroniTemplate = `# Generated by netbox-tool — do not edit manually.
scope: {{.Scope}}
name: {{.NodeName}}
namespace: /service/

restapi:
  listen: {{.NodeAddr}}:8008
  connect_address: {{.NodeAddr}}:8008
  authentication:
    username: {{.RESTUsername}}
    password: {{.RESTPassword}}

raft:
  self_addr: {{.RaftSelfAddr}}
  partner_addrs:
{{.RaftPartnerLines}}
{{- if .HasWitness}}
  - {{.WitnessAddr}}
{{- end}}

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_wal_senders: 5
        max_replication_slots: 5
        wal_log_hints: "on"

  initdb:
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: {{.ConnectAddr}}:{{.Port}}
  connect_address: {{.ConnectAddr}}:{{.Port}}
  data_dir: {{.DataDir}}
  bin_dir: {{.BinDir}}
  pgpass: /tmp/.pgpass-{{.Scope}}
  authentication:
    replication:
      username: {{.DBReplicaUser}}
      password: {{.DBReplicaPass}}
    superuser:
      username: {{.DBSuperUser}}
      password: {{.DBSuperPass}}
    rewind:
      username: {{.DBSuperUser}}
      password: {{.DBSuperPass}}
  parameters:
    unix_socket_directories: '/var/run/postgresql'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
`
