package configgen

import (
	"bytes"
	"fmt"
	"text/template"
)

// PGBackRestRepo holds configuration for one pgBackRest repository (repo1–repo4).
type PGBackRestRepo struct {
	Index     int    // 1–4
	RepoType  string // "posix", "s3", "gcs", "azure", "sftp"
	Label     string // human-readable label (not written to config)

	// posix
	PosixPath string

	// s3 / s3-compatible
	S3Bucket   string
	S3Region   string
	S3Endpoint string // empty = AWS default
	S3KeyID    string
	S3Secret   string

	// gcs
	GCSBucket string
	GCSKey    string // service account JSON key

	// azure
	AzureAccount   string
	AzureContainer string
	AzureKey       string

	// sftp
	SFTPHost       string
	SFTPPort       int
	SFTPUser       string
	SFTPPrivateKey string
	SFTPPath       string

	// retention
	FullRetention    int // repo{N}-retention-full
	DiffRetention    int // repo{N}-retention-diff
	WALRetentionDays int // repo{N}-retention-archive (in days, time-based)
}

// PGBackRestInput holds all variables needed to render a pgbackrest.conf.
type PGBackRestInput struct {
	Stanza  string          // Patroni scope — used as the stanza name
	DataDir string          // PostgreSQL data directory (pg1-path)
	Repos   []PGBackRestRepo
}

// RenderPGBackRest renders a complete pgbackrest.conf for a cluster node.
func RenderPGBackRest(in PGBackRestInput) (string, error) {
	if in.DataDir == "" {
		in.DataDir = "/var/lib/postgresql/17/main"
	}

	for i := range in.Repos {
		r := &in.Repos[i]
		if r.FullRetention == 0 {
			r.FullRetention = 2
		}
		if r.DiffRetention == 0 {
			r.DiffRetention = 7
		}
		if r.WALRetentionDays == 0 {
			r.WALRetentionDays = 14
		}
		if r.RepoType == "sftp" && r.SFTPPort == 0 {
			r.SFTPPort = 22
		}
	}

	tmpl, err := template.New("pgbackrest").Funcs(template.FuncMap{
		"repoPrefix": func(idx int) string { return fmt.Sprintf("repo%d", idx) },
	}).Parse(pgbackrestTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing pgbackrest template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, in); err != nil {
		return "", fmt.Errorf("rendering pgbackrest config: %w", err)
	}
	return buf.String(), nil
}

const pgbackrestTemplate = `# Generated by netbox-conductor — do not edit manually.
[global]
{{- range .Repos}}
{{repoPrefix .Index}}-type={{.RepoType}}
{{- if eq .RepoType "posix"}}
{{repoPrefix .Index}}-path={{.PosixPath}}
{{- end}}
{{- if eq .RepoType "s3"}}
{{repoPrefix .Index}}-s3-bucket={{.S3Bucket}}
{{repoPrefix .Index}}-s3-region={{.S3Region}}
{{- if .S3Endpoint}}
{{repoPrefix .Index}}-s3-endpoint={{.S3Endpoint}}
{{- end}}
{{repoPrefix .Index}}-s3-key={{.S3KeyID}}
{{repoPrefix .Index}}-s3-key-secret={{.S3Secret}}
{{- end}}
{{- if eq .RepoType "gcs"}}
{{repoPrefix .Index}}-gcs-bucket={{.GCSBucket}}
{{repoPrefix .Index}}-gcs-key={{.GCSKey}}
{{- end}}
{{- if eq .RepoType "azure"}}
{{repoPrefix .Index}}-azure-account={{.AzureAccount}}
{{repoPrefix .Index}}-azure-container={{.AzureContainer}}
{{repoPrefix .Index}}-azure-key={{.AzureKey}}
{{- end}}
{{- if eq .RepoType "sftp"}}
{{repoPrefix .Index}}-sftp-host={{.SFTPHost}}
{{repoPrefix .Index}}-sftp-port={{.SFTPPort}}
{{repoPrefix .Index}}-sftp-user={{.SFTPUser}}
{{repoPrefix .Index}}-sftp-private-key-file=/etc/pgbackrest/repo{{.Index}}-sftp.key
{{repoPrefix .Index}}-path={{.SFTPPath}}
{{- end}}
{{repoPrefix .Index}}-retention-full={{.FullRetention}}
{{repoPrefix .Index}}-retention-diff={{.DiffRetention}}
{{repoPrefix .Index}}-retention-archive-type=full
{{repoPrefix .Index}}-retention-archive={{.FullRetention}}
{{end}}
[{{.Stanza}}]
pg1-path={{.DataDir}}
`
