package configgen

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"text/template"
)

// SentinelInput holds the variables needed to render a sentinel.conf for one node.
type SentinelInput struct {
	// Scope is the Patroni/cluster scope — used as the monitored master name.
	Scope string

	// MasterHost is the current primary's IP (used for initial seeding).
	MasterHost string
	// MasterPort is the Postgres port (default 5432).
	MasterPort int

	// Quorum is the number of Sentinels required to agree on a failover (usually 2).
	Quorum int

	// BindAddr is the IP Sentinel listens on (empty = 0.0.0.0).
	BindAddr string
	// Port is the Sentinel port (default 26379).
	Port int

	// Password is the Redis AUTH password for both Sentinel and Redis.
	Password string

	// DownAfterMs is the milliseconds before a master is considered down (default 5000).
	DownAfterMs int
	// FailoverTimeoutMs is the failover timeout in milliseconds (default 10000).
	FailoverTimeoutMs int
}

// RenderSentinel renders a sentinel.conf from the given input.
// Returns the rendered content and its SHA-256 hex digest.
func RenderSentinel(in SentinelInput) (content, sha256hex string, err error) {
	if in.MasterPort == 0 {
		in.MasterPort = 5432
	}
	if in.Port == 0 {
		in.Port = 26379
	}
	if in.Quorum == 0 {
		in.Quorum = 2
	}
	if in.DownAfterMs == 0 {
		in.DownAfterMs = 5000
	}
	if in.FailoverTimeoutMs == 0 {
		in.FailoverTimeoutMs = 10000
	}
	if in.BindAddr == "" {
		in.BindAddr = "0.0.0.0"
	}

	tmpl, err := template.New("sentinel").Parse(sentinelTemplate)
	if err != nil {
		return "", "", fmt.Errorf("parsing sentinel template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, in); err != nil {
		return "", "", fmt.Errorf("rendering sentinel config: %w", err)
	}

	content = buf.String()
	sum := sha256.Sum256([]byte(content))
	return content, fmt.Sprintf("%x", sum[:]), nil
}

const sentinelTemplate = `# Generated by netbox-conductor — do not edit manually.
bind {{.BindAddr}}
port {{.Port}}
{{- if .Password}}
requirepass {{.Password}}
sentinel auth-pass {{.Scope}} {{.Password}}
{{- end}}

sentinel monitor {{.Scope}} {{.MasterHost}} {{.MasterPort}} {{.Quorum}}
sentinel down-after-milliseconds {{.Scope}} {{.DownAfterMs}}
sentinel failover-timeout {{.Scope}} {{.FailoverTimeoutMs}}
sentinel parallel-syncs {{.Scope}} 1
`
